// lidForm
export const UPDATE_CONTACT_TYPE_BUTTONS = 'UPDATE_CONTACT_TYPE_BUTTONS'
export const UPDATE_CONTACT_TYPE = 'UPDATE_CONTACT_TYPE'
export const UPDATE_CHECK = 'UPDATE_CHECK'
export const UPDATE_NAME = 'UPDATE_NAME'
export const UPDATE_PHONE = 'UPDATE_PHONE'
export const UPDATE_ERROR_VALUE = 'UPDATE_ERROR_VALUE'
export const UPDATE_LID_SOURCE = 'UPDATE_LID_SOURCE'
export const UPDATE_COUNTRY_CODE = 'UPDATE_COUNTRY_CODE'
export const UPDATE_NEED_OF_COMMUNICATION = 'UPDATE_NEED_OF_COMMUNICATION'

// modal
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION'

// faq
export const UPDATE_QUESTIONS = 'UPDATE_QUESTIONS'

// calculators
export const UPDATE_ORDER_QUANTITY = 'UPDATE_ORDER_QUANTITY'
export const UPDATE_ITEM_PRICE = 'UPDATE_ITEM_PRICE'
export const UPDATE_PROCEEDS_VALUE = 'UPDATE_PROCEEDS_VALUE'
export const UPDATE_VISITORS_AMOUNT = 'UPDATE_VISITORS_AMOUNT'
export const UPDATE_ORDER_PER_MONTH = 'UPDATE_ORDER_PER_MONTH'
export const UPDATE_SUCCESS_ORDER_PER_MONTH = 'UPDATE_SUCCESS_ORDER_PER_MONTH'
export const UPDATE_CONVERSION_PERCENT = 'UPDATE_CONVERSION_PERCENT'
export const UPDATE_CONVERSION_SUCCESS_PERCENT = 'UPDATE_CONVERSION_SUCCESS_PERCENT'
export const UPDATE_NEED_LID = 'UPDATE_NEED_LID'
export const UPDATE_NEED_VISITORS = 'UPDATE_NEED_VISITORS'
export const UPDATE_COST_PER_CLICK = 'UPDATE_COST_PER_CLICK'
export const UPDATE_BUDGET_AMOUNT = 'UPDATE_BUDGET_AMOUNT'
export const UPDATE_FINAL_CALC_ERROR = 'UPDATE_FINAL_CALC_ERROR'

// loader
export const UPDATE_LOADING = 'UPDATE_LOADING'

// banners
export const UPDATE_BANNERS = 'UPDATE_BANNERS'

// cases
export const UPDATE_CASES = 'UPDATE_CASES'
export const UPDATE_CASES_LOAD_STATUS = 'UPDATE_CASES_LOAD_STATUS'

// magnets
export const UPDATE_MAGNETS = 'UPDATE_MAGNETS'
export const UPDATE_MAGNETS_ID = 'UPDATE_MAGNETS_ID'
export const UPDATE_MAGNETS_REDIRECT_LINK = 'UPDATE_MAGNETS_REDIRECT_LINK'
export const UPDATE_MAGNETS_STATUS = 'UPDATE_MAGNETS_STATUS'

// post
export const UPDATE_POST_VALUES = 'UPDATE_POST_VALUES'
export const UPDATE_POST_STATUS = 'UPDATE_POST_STATUS'

// reviews
export const UPDATE_REVIEWS = 'UPDATE_REVIEWS'
export const UPDATE_REVIEWS_CATEGORY = 'UPDATE_REVIEWS_CATEGORY'
export const UPDATE_REVIEWS_LOADING = 'UPDATE_REVIEWS_LOADING'
export const UPDATE_REVIEWS_STATUS = 'UPDATE_REVIEWS_STATUS'

// faq
export const UPDATE_ACTIVE_CATEGORY = 'UPDATE_ACTIVE_CATEGORY'

// notify
export const UPDATE_NOTIFY = 'UPDATE_NOTIFY'

// product-landing
export const UPDATE_PRODUCT_MODAL_VISIBILITY = 'UPDATE_PRODUCT_MODAL_VISIBILITY'
export const UPDATE_PRODUCT_BUY_METHOD = 'UPDATE_PRODUCT_BUY_METHOD'


